server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-p1xvx2q4.cd.tencentcdb.com:10080/clothesppsdb?useSSL=false&useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.code.entity
  mapper-locations: classpath:mapper/*.xml
